# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewModel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewModel
  pod 'RxSwift',    '~> 4.4.0'
  pod 'RxAtomic',   '~> 4.4.0'
  pod 'RxCocoa',    '~> 4.4.0'
  pod 'Swinject'

end



